export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const ROUTE_CHANGE = "ROUTE_CHANGE";

export const PLAYER_INITIALIZED = "PLAYER_INITIALIZED";

export const PLAYER_FINISHED = "PLAYER_FINISHED";
